[Tree List Feature] TreeInfo Fix: layout & image logic
TreeMama/iSeaTree-React-Prototype pull request #349
Opened 2022-12-06 18:59 UTC by dddwj

## What's changed 
- fix TreeInfo modal layout (Push icon to from top-left to top-right corner)
- fix TreeInfo image list logic (Always show `FULL_PIC_1024x768` image before showing `THUMB_PIC_1024x768` images)

2022-12-06 19:05 UTC, bestw07 approved these changes

2022-12-07 03:19 UTC, bestw07 requested changes
line number 98 change 'let' to 'const' please.

2022-12-07 05:15 UTC, dddwj commented
Thanks @bestw07 for pointing that out! Just fixed that with a newer commit.

2022-12-07 18:55 UTC, bestw07 commented
> Thanks @bestw07 for pointing that out! Just fixed that with a newer commit.

welcome, @dddwj . great work!

2022-12-07 18:56 UTC, bestw07 approved these changes

2022-12-07 18:57 UTC, merged