android build
TreeMama/iSeaTree-React-Prototype pull request #537
Opened 2023-09-05 17:27 UTC by bestw07

2023-09-05 20:05 UTC, TreeMama approved these changes
ship it

2023-09-05 20:12 UTC, TreeMama requested changes
version should be 4.1.7 I think

2023-09-06 10:30 UTC, bestw07 commented
ok, I upgraded the version string and build number for android

2023-09-06 13:30 UTC, TreeMama approved these changes
changes approved!

2023-09-06 13:59 UTC, merged